import '../../models/pc_component_model.dart';
import '../../models/pc_build_model.dart';
import '../../models/order_model.dart';

class AppData {
  // Hero Banners
  static const List<Map<String, String>> heroBanners = [
    {
      'title': 'Build Your Dream Rig',
      'subtitle': 'Live Compatibility Check & Free Express Assembly',
      'badge': 'NEW ARRIVALS 2026',
      'imageUrl': 'https://images.unsplash.com/photo-1587202372775-e229f172b9d7?auto=format&fit=crop&w=1200&q=80',
      'cta': 'Start Customizing',
    },
    {
      'title': 'NVIDIA RTX 40-SUPER Series',
      'subtitle': 'Peak 4K Ray Tracing & DLSS 3.5 Frame Gen',
      'badge': 'HOT HARDWARE',
      'imageUrl': 'https://images.unsplash.com/photo-1591799264318-7e6ef8ddb7ea?auto=format&fit=crop&w=1200&q=80',
      'cta': 'Explore GPUs',
    },
    {
      'title': 'Creator Workstations',
      'subtitle': 'Ryzen 9 & Intel Core i9 for 3D & 8K Video',
      'badge': 'PRO GRADE',
      'imageUrl': 'https://images.unsplash.com/photo-1593640408182-31c70c8268f5?auto=format&fit=crop&w=1200&q=80',
      'cta': 'View Builds',
    },
  ];

  // --- PC Component Catalog with Network Images & BDT (৳) Pricing ---
  static const List<PcComponent> allComponents = [
    // === CPUs ===
    PcComponent(
      id: 'cpu_1',
      category: ComponentCategory.cpu,
      name: 'AMD Ryzen 7 7800X3D',
      brand: 'AMD',
      price: 42500,
      wattage: 120,
      socket: 'AM5',
      imageUrl: 'https://images.unsplash.com/photo-1591799264318-7e6ef8ddb7ea?auto=format&fit=crop&w=600&q=80',
      specs: {
        'Cores / Threads': '8 Cores / 16 Threads',
        'Base / Boost Clock': '4.2 GHz / 5.0 GHz',
        'Socket': 'AM5',
        'L3 Cache': '96MB 3D V-Cache',
        'TDP': '120W',
      },
      rating: 4.9,
      reviewCount: 342,
      badge: 'Best Gaming CPU',
    ),
    PcComponent(
      id: 'cpu_2',
      category: ComponentCategory.cpu,
      name: 'Intel Core i7-14700K',
      brand: 'Intel',
      price: 46000,
      wattage: 253,
      socket: 'LGA1700',
      imageUrl: 'https://images.unsplash.com/photo-1555680202-c86f0e12f086?auto=format&fit=crop&w=600&q=80',
      specs: {
        'Cores / Threads': '20 Cores (8P + 12E) / 28 Threads',
        'Max Turbo Clock': '5.6 GHz',
        'Socket': 'LGA1700',
        'L3 Cache': '33MB Intel Smart Cache',
        'TDP': '125W (Max 253W)',
      },
      rating: 4.8,
      reviewCount: 215,
      badge: 'Creator Choice',
    ),
    PcComponent(
      id: 'cpu_3',
      category: ComponentCategory.cpu,
      name: 'AMD Ryzen 5 7600X',
      brand: 'AMD',
      price: 24500,
      wattage: 105,
      socket: 'AM5',
      imageUrl: 'https://images.unsplash.com/photo-1591799264318-7e6ef8ddb7ea?auto=format&fit=crop&w=600&q=80',
      specs: {
        'Cores / Threads': '6 Cores / 12 Threads',
        'Boost Clock': '5.3 GHz',
        'Socket': 'AM5',
        'L3 Cache': '32MB',
      },
      rating: 4.7,
      reviewCount: 180,
      badge: 'Best Value',
    ),
    PcComponent(
      id: 'cpu_4',
      category: ComponentCategory.cpu,
      name: 'Intel Core i9-14900KS',
      brand: 'Intel',
      price: 78000,
      wattage: 320,
      socket: 'LGA1700',
      imageUrl: 'https://images.unsplash.com/photo-1555680202-c86f0e12f086?auto=format&fit=crop&w=600&q=80',
      specs: {
        'Cores / Threads': '24 Cores / 32 Threads',
        'Max Turbo Clock': '6.2 GHz',
        'Socket': 'LGA1700',
        'L3 Cache': '36MB',
      },
      rating: 4.9,
      reviewCount: 94,
      badge: 'Ultimate Power',
    ),

    // === Motherboards ===
    PcComponent(
      id: 'mobo_1',
      category: ComponentCategory.motherboard,
      name: 'ASUS ROG STRIX B650-A Gaming WiFi',
      brand: 'ASUS',
      price: 28000,
      wattage: 45,
      socket: 'AM5',
      memoryType: 'DDR5',
      formFactor: 'ATX',
      imageUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=600&q=80',
      specs: {
        'Socket': 'AM5',
        'Memory': '4x DDR5 (Up to 7600+ MHz)',
        'Form Factor': 'ATX',
        'WiFi': 'WiFi 6E + Bluetooth 5.2',
        'PCIe': 'PCIe 5.0 M.2 Support',
      },
      rating: 4.8,
      reviewCount: 120,
      badge: 'Top Pick',
    ),
    PcComponent(
      id: 'mobo_2',
      category: ComponentCategory.motherboard,
      name: 'MSI MAG Z790 TOMAHAWK MAX WIFI',
      brand: 'MSI',
      price: 34000,
      wattage: 50,
      socket: 'LGA1700',
      memoryType: 'DDR5',
      formFactor: 'ATX',
      imageUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=600&q=80',
      specs: {
        'Socket': 'LGA1700',
        'Memory': '4x DDR5 (Up to 7800+ MHz)',
        'Form Factor': 'ATX',
        'WiFi': 'WiFi 7 + Bluetooth 5.4',
        'PCIe': 'PCIe 5.0 x16 Slot',
      },
      rating: 4.8,
      reviewCount: 160,
      badge: 'Robust VRM',
    ),
    PcComponent(
      id: 'mobo_3',
      category: ComponentCategory.motherboard,
      name: 'Gigabyte B650M AORUS ELITE AX',
      brand: 'Gigabyte',
      price: 19500,
      wattage: 40,
      socket: 'AM5',
      memoryType: 'DDR5',
      formFactor: 'Micro-ATX',
      imageUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=600&q=80',
      specs: {
        'Socket': 'AM5',
        'Memory': '4x DDR5 (Up to 6666 MHz)',
        'Form Factor': 'Micro-ATX',
        'WiFi': 'WiFi 6E',
      },
      rating: 4.6,
      reviewCount: 95,
      badge: 'Budget Matx',
    ),

    // === Graphics Cards (GPU) ===
    PcComponent(
      id: 'gpu_1',
      category: ComponentCategory.gpu,
      name: 'NVIDIA GeForce RTX 4080 SUPER 16GB',
      brand: 'ASUS TUF',
      price: 145000,
      wattage: 320,
      imageUrl: 'https://images.unsplash.com/photo-1587202372634-32705e3bf49c?auto=format&fit=crop&w=600&q=80',
      specs: {
        'VRAM': '16GB GDDR6X',
        'Core Clock': '2550 MHz Boost',
        'Ray Tracing': '3rd Gen RT Cores',
        'DLSS': 'DLSS 3.5 Frame Generation',
        'Outputs': '3x DP 1.4a, 2x HDMI 2.1a',
      },
      rating: 4.9,
      reviewCount: 210,
      badge: '4K Ultra Champion',
    ),
    PcComponent(
      id: 'gpu_2',
      category: ComponentCategory.gpu,
      name: 'NVIDIA GeForce RTX 4070 Ti SUPER 16GB',
      brand: 'MSI Gaming X Slim',
      price: 108000,
      wattage: 285,
      imageUrl: 'https://images.unsplash.com/photo-1587202372634-32705e3bf49c?auto=format&fit=crop&w=600&q=80',
      specs: {
        'VRAM': '16GB GDDR6X',
        'Core Clock': '2670 MHz Boost',
        'CUDA Cores': '8448',
        'DLSS': 'DLSS 3.5 Supported',
      },
      rating: 4.8,
      reviewCount: 175,
      badge: 'Sweet Spot',
    ),
    PcComponent(
      id: 'gpu_3',
      category: ComponentCategory.gpu,
      name: 'AMD Radeon RX 7800 XT 16GB',
      brand: 'Sapphire Nitro+',
      price: 68000,
      wattage: 263,
      imageUrl: 'https://images.unsplash.com/photo-1587202372634-32705e3bf49c?auto=format&fit=crop&w=600&q=80',
      specs: {
        'VRAM': '16GB GDDR6',
        'Boost Clock': '2565 MHz',
        'Stream Processors': '3840',
        'FSR': 'FSR 3.1 Supported',
      },
      rating: 4.8,
      reviewCount: 140,
      badge: '1440p King',
    ),
    PcComponent(
      id: 'gpu_4',
      category: ComponentCategory.gpu,
      name: 'NVIDIA GeForce RTX 4090 24GB Founders Edition',
      brand: 'NVIDIA',
      price: 255000,
      wattage: 450,
      imageUrl: 'https://images.unsplash.com/photo-1587202372634-32705e3bf49c?auto=format&fit=crop&w=600&q=80',
      specs: {
        'VRAM': '24GB GDDR6X',
        'Boost Clock': '2520 MHz',
        'CUDA Cores': '16384',
        'Ray Tracing': 'Peak 4K/8K Gaming',
      },
      rating: 5.0,
      reviewCount: 88,
      badge: 'Flagship Titan',
    ),

    // === Memory (RAM) ===
    PcComponent(
      id: 'ram_1',
      category: ComponentCategory.ram,
      name: 'Corsair Vengeance RGB 32GB (2x16GB) DDR5 6000MHz',
      brand: 'Corsair',
      price: 14500,
      wattage: 15,
      memoryType: 'DDR5',
      imageUrl: 'https://images.unsplash.com/photo-1562976540-1502c2145186?auto=format&fit=crop&w=600&q=80',
      specs: {
        'Capacity': '32GB (2x16GB)',
        'Speed': '6000 MHz CL30',
        'Type': 'DDR5',
        'RGB': 'Dynamic Multi-Zone RGB',
        'Profile': 'AMD EXPO & Intel XMP 3.0',
      },
      rating: 4.9,
      reviewCount: 310,
      badge: 'Top Seller',
    ),
    PcComponent(
      id: 'ram_2',
      category: ComponentCategory.ram,
      name: 'G.SKILL Trident Z5 RGB 64GB (2x32GB) DDR5 6400MHz',
      brand: 'G.SKILL',
      price: 27000,
      wattage: 20,
      memoryType: 'DDR5',
      imageUrl: 'https://images.unsplash.com/photo-1562976540-1502c2145186?auto=format&fit=crop&w=600&q=80',
      specs: {
        'Capacity': '64GB (2x32GB)',
        'Speed': '6400 MHz CL32',
        'Type': 'DDR5',
        'RGB': 'Full-length RGB Light Bar',
      },
      rating: 4.9,
      reviewCount: 145,
      badge: 'Workstation Pro',
    ),
    PcComponent(
      id: 'ram_3',
      category: ComponentCategory.ram,
      name: 'TeamGroup T-Force Delta RGB 32GB (2x16GB) DDR5 5600MHz',
      brand: 'TeamGroup',
      price: 11500,
      wattage: 15,
      memoryType: 'DDR5',
      imageUrl: 'https://images.unsplash.com/photo-1562976540-1502c2145186?auto=format&fit=crop&w=600&q=80',
      specs: {
        'Capacity': '32GB (2x16GB)',
        'Speed': '5600 MHz CL36',
        'Type': 'DDR5',
      },
      rating: 4.7,
      reviewCount: 90,
      badge: 'Budget RGB',
    ),

    // === Storage (SSD) ===
    PcComponent(
      id: 'ssd_1',
      category: ComponentCategory.storage,
      name: 'Samsung 990 PRO 2TB PCIe 4.0 NVMe M.2 SSD',
      brand: 'Samsung',
      price: 21500,
      wattage: 10,
      imageUrl: 'https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?auto=format&fit=crop&w=600&q=80',
      specs: {
        'Capacity': '2TB',
        'Read Speed': 'Up to 7,450 MB/s',
        'Write Speed': 'Up to 6,900 MB/s',
        'Interface': 'PCIe Gen 4.0 x4, NVMe 2.0',
        'Endurance': '1200 TBW',
      },
      rating: 4.9,
      reviewCount: 420,
      badge: 'Blazing Fast',
    ),
    PcComponent(
      id: 'ssd_2',
      category: ComponentCategory.storage,
      name: 'Crucial T700 2TB PCIe Gen5 NVMe M.2 SSD with Heatsink',
      brand: 'Crucial',
      price: 35000,
      wattage: 14,
      imageUrl: 'https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?auto=format&fit=crop&w=600&q=80',
      specs: {
        'Capacity': '2TB',
        'Read Speed': 'Up to 12,400 MB/s',
        'Write Speed': 'Up to 11,800 MB/s',
        'Interface': 'PCIe Gen 5.0 x4',
      },
      rating: 4.8,
      reviewCount: 82,
      badge: 'Next-Gen Gen5',
    ),
    PcComponent(
      id: 'ssd_3',
      category: ComponentCategory.storage,
      name: 'WD_BLACK SN770 1TB NVMe SSD',
      brand: 'Western Digital',
      price: 9500,
      wattage: 8,
      imageUrl: 'https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?auto=format&fit=crop&w=600&q=80',
      specs: {
        'Capacity': '1TB',
        'Read Speed': 'Up to 5,150 MB/s',
        'Interface': 'PCIe Gen 4.0 x4',
      },
      rating: 4.7,
      reviewCount: 260,
      badge: 'Best Value',
    ),

    // === Power Supply (PSU) ===
    PcComponent(
      id: 'psu_1',
      category: ComponentCategory.psu,
      name: 'Corsair RM850x 850W 80 Plus Gold Fully Modular',
      brand: 'Corsair',
      price: 16500,
      wattage: 0,
      imageUrl: 'https://images.unsplash.com/photo-1587202372583-49330a15584d?auto=format&fit=crop&w=600&q=80',
      specs: {
        'Wattage': '850W',
        'Efficiency': '80 PLUS Gold Certified',
        'Modularity': 'Fully Modular',
        'Fan': '135mm Magnetic Levitation Fan',
        'Standard': 'ATX 3.0 / PCIe 5.0 Ready',
      },
      rating: 4.9,
      reviewCount: 310,
      badge: 'Gold Standard',
    ),
    PcComponent(
      id: 'psu_2',
      category: ComponentCategory.psu,
      name: 'Seasonic Vertex GX-1000 1000W 80 Plus Gold ATX 3.0',
      brand: 'Seasonic',
      price: 24000,
      wattage: 0,
      imageUrl: 'https://images.unsplash.com/photo-1587202372583-49330a15584d?auto=format&fit=crop&w=600&q=80',
      specs: {
        'Wattage': '1000W',
        'Efficiency': '80 PLUS Gold Certified',
        'Modularity': 'Fully Modular',
        'Connector': 'Native 12VHPWR Cable for RTX 40-Series',
      },
      rating: 5.0,
      reviewCount: 95,
      badge: 'Heavy Duty',
    ),
    PcComponent(
      id: 'psu_3',
      category: ComponentCategory.psu,
      name: 'MSI MAG A750GL PCIE5 750W 80 Plus Gold',
      brand: 'MSI',
      price: 11500,
      wattage: 0,
      imageUrl: 'https://images.unsplash.com/photo-1587202372583-49330a15584d?auto=format&fit=crop&w=600&q=80',
      specs: {
        'Wattage': '750W',
        'Efficiency': '80 PLUS Gold',
        'Modularity': 'Fully Modular',
      },
      rating: 4.7,
      reviewCount: 110,
      badge: 'Best Value',
    ),

    // === CPU Coolers ===
    PcComponent(
      id: 'cooler_1',
      category: ComponentCategory.cooler,
      name: 'NZXT Kraken Elite 360 RGB Liquid Cooler',
      brand: 'NZXT',
      price: 32000,
      wattage: 25,
      imageUrl: 'https://images.unsplash.com/photo-1587202372775-e229f172b9d7?auto=format&fit=crop&w=600&q=80',
      specs: {
        'Radiator Size': '360mm Aluminum',
        'Screen': '2.36" Wide-Angle LCD Display',
        'Fans': '3x 120mm F120 RGB Core Fans',
        'Compatibility': 'Intel LGA1700 / AMD AM5 & AM4',
      },
      rating: 4.9,
      reviewCount: 220,
      badge: 'LCD Display',
    ),
    PcComponent(
      id: 'cooler_2',
      category: ComponentCategory.cooler,
      name: 'DeepCool AK620 Digital Dual-Tower Air Cooler',
      brand: 'DeepCool',
      price: 8500,
      wattage: 10,
      imageUrl: 'https://images.unsplash.com/photo-1587202372775-e229f172b9d7?auto=format&fit=crop&w=600&q=80',
      specs: {
        'Type': 'Dual-Tower 6-Heatpipe Cooler',
        'Display': 'Real-time CPU Status Screen',
        'Fans': '2x 120mm FDB Fans',
        'TDP Rating': 'Up to 260W',
      },
      rating: 4.8,
      reviewCount: 190,
      badge: 'Top Air Cooler',
    ),

    // === PC Cases (Casing) ===
    PcComponent(
      id: 'case_1',
      category: ComponentCategory.casing,
      name: 'Lian Li O11 Dynamic EVO RGB Showcase',
      brand: 'Lian Li',
      price: 19000,
      wattage: 0,
      formFactor: 'ATX',
      imageUrl: 'https://images.unsplash.com/photo-1593640408182-31c70c8268f5?auto=format&fit=crop&w=600&q=80',
      specs: {
        'Form Factor': 'Mid Tower Dual Chamber',
        'Glass': 'Front & Side Tempered Glass',
        'RGB': 'Dual ARGB Strips (Top & Bottom)',
        'Radiator Support': 'Up to 3x 360mm Radiators',
      },
      rating: 4.9,
      reviewCount: 380,
      badge: 'Showcase Favorite',
    ),
    PcComponent(
      id: 'case_2',
      category: ComponentCategory.casing,
      name: 'NZXT H9 Flow Panoramic Dual-Chamber Case',
      brand: 'NZXT',
      price: 22500,
      wattage: 0,
      formFactor: 'ATX',
      imageUrl: 'https://images.unsplash.com/photo-1593640408182-31c70c8268f5?auto=format&fit=crop&w=600&q=80',
      specs: {
        'Type': 'Panoramic Glass Mid-Tower',
        'Fans Included': '4x 120mm Quiet Airflow Fans',
        'Cooling': 'High Airflow Perforated Top Panel',
      },
      rating: 4.9,
      reviewCount: 140,
      badge: 'Maximum Airflow',
    ),
    PcComponent(
      id: 'case_3',
      category: ComponentCategory.casing,
      name: 'Corsair 4000D Airflow Tempered Glass',
      brand: 'Corsair',
      price: 10500,
      wattage: 0,
      formFactor: 'ATX',
      imageUrl: 'https://images.unsplash.com/photo-1593640408182-31c70c8268f5?auto=format&fit=crop&w=600&q=80',
      specs: {
        'Type': 'Mid-Tower High Airflow',
        'Cable Management': 'RapidRoute System',
      },
      rating: 4.8,
      reviewCount: 520,
      badge: 'Best Seller Case',
    ),
  ];

  // --- Featured Pre-built Gaming Rigs & Workstations (in BDT ৳) ---
  static final List<PcBuildModel> featuredPrebuilts = [
    PcBuildModel(
      id: 'rig_1',
      title: 'Vortex Titan Ultra 4K',
      tier: 'Ultimate Gaming',
      price: 315000.00,
      originalPrice: 340000.00,
      rating: 4.9,
      reviews: 128,
      description: 'The pinnacle of 4K ultra gaming and ray tracing. Built with Ryzen 7 7800X3D and NVIDIA RTX 4080 Super with premium liquid cooling and Lian Li glass showcase.',
      imageUrl: 'https://images.unsplash.com/photo-1587202372775-e229f172b9d7?auto=format&fit=crop&w=800&q=80',
      cpu: 'AMD Ryzen 7 7800X3D (8C/16T)',
      gpu: 'NVIDIA RTX 4080 SUPER 16GB',
      ram: '32GB Corsair DDR5 6000MHz RGB',
      storage: '2TB Samsung 990 PRO Gen4 NVMe',
      motherboard: 'ASUS ROG STRIX B650-A Gaming WiFi',
      psu: 'Corsair RM850x 850W Gold Fully Modular',
      cooler: 'NZXT Kraken Elite 360 RGB Liquid Cooler',
      casing: 'Lian Li O11 Dynamic EVO RGB',
      totalWattage: 620,
      tags: ['4K Ultra 144Hz+', 'Ray Tracing DLSS 3.5', 'Liquid Cooled', 'VR Ready'],
      badge: 'BESTSELLER',
      isFeatured: true,
      defaultComponents: [
        allComponents.firstWhere((c) => c.id == 'cpu_1'),
        allComponents.firstWhere((c) => c.id == 'mobo_1'),
        allComponents.firstWhere((c) => c.id == 'gpu_1'),
        allComponents.firstWhere((c) => c.id == 'ram_1'),
        allComponents.firstWhere((c) => c.id == 'ssd_1'),
        allComponents.firstWhere((c) => c.id == 'psu_1'),
        allComponents.firstWhere((c) => c.id == 'cooler_1'),
        allComponents.firstWhere((c) => c.id == 'case_1'),
      ],
    ),
    PcBuildModel(
      id: 'rig_2',
      title: 'CyberForge Studio Pro',
      tier: 'Creator & 3D Workstation',
      price: 495000.00,
      originalPrice: 530000.00,
      rating: 5.0,
      reviews: 64,
      description: 'Engineered for intensive 3D rendering, 8K video editing, AI workflows, and multi-threaded simulations.',
      imageUrl: 'https://images.unsplash.com/photo-1593640408182-31c70c8268f5?auto=format&fit=crop&w=800&q=80',
      cpu: 'Intel Core i9-14900KS (24C/32T 6.2GHz)',
      gpu: 'NVIDIA RTX 4090 24GB Founders Edition',
      ram: '64GB G.SKILL Trident Z5 DDR5 6400MHz',
      storage: '2TB Crucial T700 Gen5 NVMe (12,400 MB/s)',
      motherboard: 'MSI MAG Z790 TOMAHAWK MAX WIFI',
      psu: 'Seasonic Vertex 1000W 80+ Gold ATX 3.0',
      cooler: 'NZXT Kraken Elite 360 RGB',
      casing: 'NZXT H9 Flow Panoramic Glass',
      totalWattage: 780,
      tags: ['8K Video Editing', 'Blender / Maya / Unreal Engine 5', 'Gen5 NVMe SSD', 'AI Compute'],
      badge: 'TOP WORKSTATION',
      isFeatured: true,
      defaultComponents: [
        allComponents.firstWhere((c) => c.id == 'cpu_4'),
        allComponents.firstWhere((c) => c.id == 'mobo_2'),
        allComponents.firstWhere((c) => c.id == 'gpu_4'),
        allComponents.firstWhere((c) => c.id == 'ram_2'),
        allComponents.firstWhere((c) => c.id == 'ssd_2'),
        allComponents.firstWhere((c) => c.id == 'psu_2'),
        allComponents.firstWhere((c) => c.id == 'cooler_1'),
        allComponents.firstWhere((c) => c.id == 'case_2'),
      ],
    ),
    PcBuildModel(
      id: 'rig_3',
      title: 'Shadow Apex 1440p Beast',
      tier: 'Competitive Gaming',
      price: 165000.00,
      originalPrice: 180000.00,
      rating: 4.8,
      reviews: 96,
      description: 'The definitive sweet spot for 1440p high-refresh gaming in titles like Warzone, Cyberpunk, Valorant, and Apex Legends.',
      imageUrl: 'https://images.unsplash.com/photo-1547082299-de196ea013d6?auto=format&fit=crop&w=800&q=80',
      cpu: 'AMD Ryzen 5 7600X 6-Core',
      gpu: 'AMD Radeon RX 7800 XT 16GB',
      ram: '32GB TeamGroup DDR5 5600MHz RGB',
      storage: '1TB WD_BLACK SN770 NVMe SSD',
      motherboard: 'Gigabyte B650M AORUS ELITE AX',
      psu: 'MSI MAG A750GL 750W Gold',
      cooler: 'DeepCool AK620 Digital Dual-Tower',
      casing: 'Corsair 4000D Airflow',
      totalWattage: 480,
      tags: ['1440p 165Hz Ready', 'FSR 3.1 & Frame Gen', 'High Airflow', 'Great Value'],
      badge: 'HOT DEAL',
      isFeatured: false,
      defaultComponents: [
        allComponents.firstWhere((c) => c.id == 'cpu_3'),
        allComponents.firstWhere((c) => c.id == 'mobo_3'),
        allComponents.firstWhere((c) => c.id == 'gpu_3'),
        allComponents.firstWhere((c) => c.id == 'ram_3'),
        allComponents.firstWhere((c) => c.id == 'ssd_3'),
        allComponents.firstWhere((c) => c.id == 'psu_3'),
        allComponents.firstWhere((c) => c.id == 'cooler_2'),
        allComponents.firstWhere((c) => c.id == 'case_3'),
      ],
    ),
  ];

  // --- Mock Orders with Tracking (in BDT ৳) ---
  static final List<OrderModel> mockOrders = [
    OrderModel(
      id: 'RC-84920',
      orderDate: 'Aug 14, 2026',
      estimatedDelivery: 'Aug 19, 2026',
      status: OrderStatus.assembly,
      totalAmount: 315000.00,
      buildName: 'Vortex Titan Custom Rig',
      items: const [
        OrderItemModel(title: 'AMD Ryzen 7 7800X3D', subtitle: 'AM5, 8C/16T', price: 42500),
        OrderItemModel(title: 'NVIDIA RTX 4080 SUPER 16GB', subtitle: 'ASUS TUF Edition', price: 145000),
        OrderItemModel(title: 'ASUS ROG Strix B650-A', subtitle: 'DDR5, WiFi 6E', price: 28000),
        OrderItemModel(title: 'Corsair Vengeance RGB 32GB', subtitle: 'DDR5 6000MHz', price: 14500),
        OrderItemModel(title: 'Samsung 990 Pro 2TB SSD', subtitle: 'Gen4 NVMe', price: 21500),
        OrderItemModel(title: 'Lian Li O11 Dynamic EVO RGB', subtitle: 'Dual-Chamber Case', price: 19000),
      ],
      shippingAddress: 'House 42, Road 11, Banani, Dhaka',
      paymentMethod: 'bKash / Nagad Verified',
      trackingNumber: 'TRK-98234871BD',
    ),
  ];

  // --- Saved Custom Builds ---
  static List<PcBuildModel> savedBuilds = [
    featuredPrebuilts[0],
    featuredPrebuilts[2],
  ];
}
